default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: cbrapp_development

test:
  <<: *default
  database: cbrapp_test

production:
  <<: *default
  database: cbrapp_production